/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 04:12:26 PM MST 
//


package com.sri.save.s3d;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S3DType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S3DType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head" type="{}HeadType"/>
 *         &lt;element name="flora_base" type="{}FloraBaseType" maxOccurs="unbounded"/>
 *         &lt;element name="semantic_mapping" type="{}SemanticMappingType"/>
 *         &lt;element name="grouping" type="{}HierGroupType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S3DType", propOrder = {
    "head",
    "floraBase",
    "semanticMapping",
    "grouping"
})
public class S3DType {

    @XmlElement(required = true)
    protected HeadType head;
    @XmlElement(name = "flora_base", required = true)
    protected List<FloraBaseType> floraBase;
    @XmlElement(name = "semantic_mapping", required = true)
    protected SemanticMappingType semanticMapping;
    @XmlElement(required = true)
    protected List<HierGroupType> grouping;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the floraBase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the floraBase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFloraBase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FloraBaseType }
     * 
     * 
     */
    public List<FloraBaseType> getFloraBase() {
        if (floraBase == null) {
            floraBase = new ArrayList<FloraBaseType>();
        }
        return this.floraBase;
    }

    /**
     * Gets the value of the semanticMapping property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticMappingType }
     *     
     */
    public SemanticMappingType getSemanticMapping() {
        return semanticMapping;
    }

    /**
     * Sets the value of the semanticMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticMappingType }
     *     
     */
    public void setSemanticMapping(SemanticMappingType value) {
        this.semanticMapping = value;
    }

    /**
     * Gets the value of the grouping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grouping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrouping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HierGroupType }
     * 
     * 
     */
    public List<HierGroupType> getGrouping() {
        if (grouping == null) {
            grouping = new ArrayList<HierGroupType>();
        }
        return this.grouping;
    }

}
